### ISSUE TITLE
Add way to retrieve stuck tokens from the contract

### ISSUE THREAD

**Issue by ajsantander** [ethernautdao/ethernauts#73]
It is a very common problem that people send tokens to the actual token contract itself, and these tokens get stuck in the contract.

I.e. people send DAI to the DAI contract. If tokens are sent to the Ethernauts.sol NFT contract, be it DAI, SNX, or even the token itself, there is currently no way of recovering them.

There are many approaches for solving this, and I suggest we take the simplest one. We allow the owner (which will be the EthernautDAO multisig or council) to withdraw the tokens, and we trust the DAO to do the right thing and return the tokens to the senders, or donate them with a vote, etc.

**Comment by 13371007** [comment]
I'll give this one a shot

**Comment by 13371007** [comment]
I need to deploy a mock erc20. 

1. I can use hardhat-waffle and call deployMockContract(), but I don't like the idea of adding a dependency for such a trivial task. 

2. Another option would be to add a MockERC20 SC to the repo. It's a little ugly, but simpler.

**Comment by StErMi** [comment]
I think that the last one (trusting the DAO with multisig) would be the best one for both simplicity and organization. If the idea is to have a real DAO I don't see the problem to also having fair votes to handle this situation, otherwise, the only choice is to go with full decentralization without having a DAO (but we should change the name of the Project :D)

Are we talking about stuck tokens because people make a mistake and send them to our contract or because people make "donations" to the DAO?
