### ISSUE TITLE
Add COMPLETED sale state

### ISSUE THREAD

**Issue by ajsantander** [ethernautdao/ethernauts#92]
On the contract side, we need a new sale state: Completed.

It means that the entire NFT collection is out-of-stock. With this, we can detect when there are no more NFTs available to mint.

**Comment by StErMi** [comment]
I usually apply this pattern on react (thanks Kant C. Dodds :D): "Don't Sync State. Derive It!"

Which is the reason behind it? The NFT sale is "ended" when `availableSupply` returns 0 right? 

If you really (I'm not using "we" because I haven't contributed to the project yet :D) do that we could introduce a new `SaleState.Completed` that is set only if `availableSupply()` returns `0` but that method would be a "waste of gas" because you could that even if there's still supply.

What we could do is to have a `getSaleState` method that return `Completed` if we are in the `Open` state but `availableSupply()` returns 0.

**Comment by slorenzo** [comment]
Yep! What you said is right and we discussed that option before. But I also think being more explicit with the sale state from the contract makes it easier and cleaner to handle it from the dapp.

For that reason, we've created a [useSaleState hook](https://github.com/ethernautdao/ethernauts/blob/main/packages/dapp/hooks/useSaleState.js#L9) to fetch the sale state from the dapp and it don't use gas becuase it's a public variable and Solidity creates a getter function by default.

**Comment by StErMi** [comment]
it would not use gas even if it was private and you would have dedicated the state as I said previously.

**Comment by StErMi** [comment]
I can make an easy and fast POC for tomorrow

**Comment by StErMi** [comment]
This is the proposal, if someone could review it I'll create a merge request https://github.com/StErMi/ethernauts/commit/c8f70721a2bfc72b21c99d63c86a0a42c623c355
